# Generated by Django 4.0.5 on 2022-06-10 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0002_alter_product_image_review'),
        ('shopApp', '0002_alter_product_image_userprofile'),
    ]

    operations = [
    ]
