# Generated by Django 4.0.5 on 2022-06-12 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0003_auto_20220610_1230'),
        ('shopApp', '0003_userprofile'),
    ]

    operations = [
    ]
