# Generated by Django 4.0.5 on 2022-06-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopApp', '0005_alter_category_id_alter_product_id_alter_review_id'),
        ('shopApp', '0005_product_favourite_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
    ]
